### ISSUE TITLE
Cannot resolve Jedis client classes with Grails 4

### ISSUE THREAD

**Issue by andersaaberg** [grails-plugins/grails-redis#83]
Lets say that I have this simple controller in Grails 3:
```
import grails.plugins.redis.RedisService
import redis.clients.jedis.Jedis

class HelloController {

    RedisService redisService

    def index() {
        redisService.withRedis { Jedis redis ->
            redis.ping()
        }
    }
}
```

this works in Grails 3.3.10 but not in Grails 4.0.0 where "./gradlew bootRun" fails with this compilation error: "unable to resolve class redis.clients.jedis.Jedis". 
This is a bit odd, as redis.clients:jedis should be available in Grails 4.0.0 according to ./gradlew dependencies.

This has forced me to use "micronaut-redis-lettuce" instead of this grails-plugin with Grails 4.0.0.

**Comment by andersaaberg** [comment]
This is probably due to that transitive dependencies are no longer resolved for plugins: http://docs.grails.org/latest/guide/upgrading.html#_upgrading_to_gradle_5
https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:pom_compile_runtime_separation

**Comment by dsvyrjm** [comment]
As per @andersaaberg answer, we need to add explicit dependency in `build.gradle`:
```Groovy
...
implementation 'redis.clients:jedis:2.9.0'
...
```
`2.9.0` version took from the `redis:2.0.5` sources

**Comment by puneetbehl** [comment]
Could you please verify if this is still an issue with current active version?

**Comment by Richardson-e** [comment]
@puneetbehl Using grails 6.1.0 and adding the dependencies
```    
implementation 'org.grails.plugins:grails-redis:3.0.0'
implementation 'redis.clients:jedis:2.9.0'
```
a project with a basic controller like the one mentioned in the original comment will compile as expected.

**Comment by puneetbehl** [comment]
@andersaaberg Please upgrade to the most recent version of the Grails framework and this plugin.
